# Generated by Django 4.2.2 on 2023-07-03 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('fathername', models.CharField(max_length=100, verbose_name='Отчество')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('phone', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('fathername', models.CharField(max_length=100, verbose_name='Отчество')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('specialization', models.CharField(choices=[('гем', 'Гематолог'), ('онк', 'Онколог'), ('тер', 'Терапевт'), ('узи', 'врач УЗИ'), ('клд', 'врач КЛД')], max_length=100, verbose_name='Специализация')),
                ('experience', models.IntegerField(verbose_name='Стаж работы')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('БАК', 'Биохимический анализ крови'), ('ОАК', 'Общий анализ крови'), ('ОНК', 'Онкотест Pantum Detect'), ('ИНС', 'Инструментальная диагностика'), ('ЦИТ', 'Цитологические исследования')], max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Spezialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('гем', 'Гематолог'), ('онк', 'Онколог'), ('тер', 'Терапевт'), ('узи', 'врач УЗИ'), ('клд', 'врач КЛД')], max_length=3)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pantum.doctors')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchesRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantum.research')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorsRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantum.doctors')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantum.clients')),
                ('doctors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantum.doctors')),
            ],
        ),
    ]
