# Generated by Django 4.2.2 on 2023-07-03 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Гематолог', 'Врач-гематолог'), ('Онколог', 'Врач-онколог'), ('Терапев', 'Врач-терапевт'), ('Врач УЗД', 'Врач ультразвуковой диагностики'), ('Врач КДЛ', 'Врач клинико-лабораторной диагностики')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='research',
            name='date',
        ),
        migrations.AddField(
            model_name='research',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='clients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pantum.clients'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='doctors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pantum.doctors'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='specialization',
            field=models.CharField(choices=[('Гематолог', 'Врач-гематолог'), ('Онколог', 'Врач-онколог'), ('Терапев', 'Врач-терапевт'), ('Врач УЗД', 'Врач ультразвуковой диагностики'), ('Врач КДЛ', 'Врач клинико-лабораторной диагностики')], max_length=100, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='doctorsrating',
            name='rating',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='researchesrating',
            name='rating',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Spezialization',
        ),
        migrations.AddField(
            model_name='doctorsspecialization',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pantum.doctors'),
        ),
    ]
