# Generated by Django 4.2.2 on 2023-07-06 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantum', '0002_doctorsspecialization_remove_research_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Клиенты', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'Консультации', 'verbose_name_plural': 'Консультации'},
        ),
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name': 'Врачи', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterModelOptions(
            name='doctorsrating',
            options={'verbose_name': 'Рейтинг врачей', 'verbose_name_plural': 'Рейтинг врачей'},
        ),
        migrations.AlterModelOptions(
            name='doctorsspecialization',
            options={'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализация'},
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name': 'Исследования', 'verbose_name_plural': 'Исследования'},
        ),
        migrations.AlterModelOptions(
            name='researchesrating',
            options={'verbose_name': 'Отзывы об исследовании', 'verbose_name_plural': 'Отзывы об исследовании'},
        ),
        migrations.AlterField(
            model_name='clients',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='clients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pantum.clients', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='doctors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pantum.doctors', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='doctorsrating',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='doctorsrating',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantum.doctors', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='doctorsrating',
            name='rating',
            field=models.PositiveIntegerField(null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='doctorsspecialization',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pantum.doctors', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='doctorsspecialization',
            name='name',
            field=models.CharField(choices=[('Гематолог', 'Врач-гематолог'), ('Онколог', 'Врач-онколог'), ('Терапев', 'Врач-терапевт'), ('Врач УЗД', 'Врач ультразвуковой диагностики'), ('Врач КДЛ', 'Врач клинико-лабораторной диагностики')], max_length=100, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='research',
            name='description',
            field=models.CharField(max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='research',
            name='name',
            field=models.CharField(choices=[('Биохимический анализ крови', 'Биохимический анализ крови'), ('Общий анализ крови', 'Общий анализ крови'), ('Pantum Detect', 'Онкотест Pantum Detect'), ('Инструментальная диагностика', 'Инструментальная диагностика'), ('Цитологические исследования', 'Цитологические исследования')], max_length=30, verbose_name='Исследование'),
        ),
        migrations.AlterField(
            model_name='researchesrating',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='researchesrating',
            name='rating',
            field=models.PositiveIntegerField(null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='researchesrating',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pantum.research', verbose_name='Исследование'),
        ),
    ]
