# Generated by Django 4.2.2 on 2023-07-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantum', '0003_alter_clients_options_alter_consultation_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorsRating',
            new_name='DoctorsReview',
        ),
        migrations.RenameModel(
            old_name='ResearchesRating',
            new_name='ResearchesReview',
        ),
    ]
