# Generated by Django 4.2.2 on 2023-07-09 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantum', '0004_rename_doctorsrating_doctorsreview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(null=True, verbose_name='Рейтинг')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('clients', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pantum.clients', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.RemoveField(
            model_name='researchesreview',
            name='research',
        ),
        migrations.DeleteModel(
            name='DoctorsReview',
        ),
        migrations.DeleteModel(
            name='ResearchesReview',
        ),
    ]
