# Generated by Django 4.2.2 on 2023-07-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantum', '0005_reviews_remove_researchesreview_research_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo_doctor'),
        ),
        migrations.AddField(
            model_name='research',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo_research'),
        ),
    ]
