# Generated by Django 4.2.2 on 2023-07-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantum', '0006_doctors_photo_research_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='doctors',
        ),
        migrations.AddField(
            model_name='consultation',
            name='service',
            field=models.CharField(max_length=100, null=True, verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo_doctor', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='research',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo_research', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
    ]
