# Generated by Django 4.2.2 on 2023-07-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantum', '0007_remove_consultation_doctors_consultation_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='phone',
            field=models.CharField(default='', max_length=40, verbose_name='Телефон'),
        ),
    ]
